on: [push]

name: Test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: '11.x'
      - uses: actions/cache@f5ce41475b483ad7581884324a6eca9f48f8dcc7 # v1
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - run: npm install
      - run: npm run test
      - run: npm run build
